# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chancemeuci', '0003_auto_20170712_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='sat_math',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicant',
            name='sat_verbal',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicant',
            name='sat_writing',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
    ]
